#pragma once
#include "Engine/GameViewportClient.h"
#include "AllowWindowsPlatformTypes.h"
#include <type_traits>
#include <iostream>
#include <string>
#include "boost/iostreams/concepts.hpp"
#include "boost/iostreams/stream_buffer.hpp"
#include "VideoRecorder.h"